use_frameworks!

platform :ios, '9.0'

target 'SSNetworkOC_Example' do
  pod 'SSNetworkOC', :path => '../'
  pod 'AFNetworking','~> 4.0.1'

  target 'SSNetworkOC_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
